version: 3
services:
  server:
    build: packages/server
    ports:
      - 4000:4000
    stdin_open: true
    environment:
      - NODE_ENV=production
      - PORT=4000
      - DEBUG=server
      - GOOGLE_CLIENT_ID=927669772833-ou0jjulc4p68dbfmfnltjqk83rgd5mtr.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=jmn2fzU9n55PIX6FwswyWcDV
      - GOOGLE_REDIRECT_URL=urn:ietf:wg:oauth:2.0:oob
  web:
    build: packages/web
    ports:
      - 4001:4001
    environment:
      - NODE_ENV=production
      - PORT=4001
      - DEBUG=web
      - API_DOMAIN=http://localhost:4000/graphql

